# Generated by Django 2.2.5 on 2021-02-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210218_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='counrty',
            new_name='country',
        ),
    ]
