# Generated by Django 2.2.5 on 2021-02-20 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20210220_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='ameities',
            new_name='amenities',
        ),
    ]
